### ISSUE TITLE
Sender address rejected: not owned by auth user By Node Mailer

### ISSUE THREAD

**Issue by ciaompe** [MinecraftForgeFrance/nodebb-plugin-contact-page#1]
In the library.js, sendMail function 1st param is users email address set to from attribute, you cannot set external domain email address while using smtp.

Original Code (library js, line 82) 
```
sendMail(req.body.email, req.body.name, req.body.subject, req.body.message, res);
```
Fix Code
```
sendMail('email@yourdomain.com', req.body.name, req.body.subject, req.body.message, res);
```

**Comment by robin4002** [comment]
Hi,
Thank for the report.

Indeed, it's was working for me because my custom SMTP server is configured to trust any message send by an authenticated user, but having a 'from' different than the authenticated user isn't a good practice and can cause some problems.
