### ISSUE TITLE
GOOGLE RE-CAPTCHA bug

### ISSUE THREAD

**Issue by chocolate012** [MinecraftForgeFrance/nodebb-plugin-contact-page#2]
Hi
for some odd reason, I have the Google Cptche enabled everything is set up fine but lately I get an Hcaptcha instead of Re-Captcha
and there is some kind of error rate limit
see https://shutfim.com/contact

**Comment by robin4002** [comment]
Hi,
Look like there is the same problem on my forum : https://www.minecraftforgefrance.fr/contact
This is indeed very wird, as there is not a single hcaptcha code in this plugin.

There is probably a conflict with another plugin, i will look at this when I have the time ...

**Comment by chocolate012** [comment]
@robin4002 It might be the nodebb-plugin-spam-be-gone that's causing it

**Comment by robin4002** [comment]
Indeed, hcaptcha support has been added in may : https://github.com/akhoury/nodebb-plugin-spam-be-gone/commit/937e06b741210966aeed2a6f1691b16b9b2289f2#diff-23d0409eda55ae4e1330ef5acbab63f8R428
And the script is loaded on every page.
Look like hcaptcha has the same API, and it override the global variable `grecaptcha` by it's own ...

After a long investigation, I finally find a simple way to fix it ;)
