### ISSUE TITLE
Clicking On Send Does Nothing

### ISSUE THREAD

**Issue by Sampo2910** [MinecraftForgeFrance/nodebb-plugin-contact-page#4]
Admin ACP updated with captcha keys and email address.

HTML added on sidebar displaying 'Contact Us' on main page. 

The page can be filled out as in your demo but when clicking on send nothing happens. No errors in logs.  Using v1.18.1

**Comment by robin4002** [comment]
Hi,

Sorry for the late response. I reproduced the bug successfully, there is an error in the logs of the browser. The function `ajaxSubmit` (used here https://github.com/MinecraftForgeFrance/nodebb-plugin-contact-page/blob/master/static/js/contact.js#L22) no longer exists in NodeBB 1.18.
I need to update the code.

Hopefully I can fix it tomorrow.

**Comment by robin4002** [comment]
Fixed in release 1.2.0 93aef2c24ba159206015f4260f9d2ecdce8b9259 ;)
